version: "3.0"
services:
  attack:
    build: ./docker/attack
    ports:
      - "8080:8080"
    networks:
      - pentest
    tty: true  
  defense:
    build: ./docker/defence
    ports:
      - "8081:8081"
    networks:
      - pentest
    tty: true 
networks:
  pentest:
    external: true